import Head from 'next/head'

import styles from '../styles/Home.module.css'
import Demo from '../../shared/components/Demo'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Demo />
      </main>
    </div>
  )
}
